# Generated by Django 4.2.2 on 2023-07-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orders_status_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Order Processing', 'Order Processing'), ('Order Recieved', 'Order Recieved'), ('On The Way', 'On the Way'), ('Order completed', 'Order completed')], default='Order Processing', max_length=250, null=True),
        ),
    ]
